name: Multipule Jobs Flow

on: 
    workflow_dispatch:

jobs:
  build-job:
    runs-on: ubuntu-latest
    steps:
      - name: Create build artifact file
        run: echo "Build job executed successfully!" > artifact.txt

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-artifact
          path: artifact.txt

  test-job:
    runs-on: ubuntu-latest
    needs: build-job
    concurrency:
      group: test-job-group
      cancel-in-progress: false
    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: build-artifact

      - name: Test artifact file
        run: |
          echo "Testing the artifact..."
          cat artifact.txt
      - name: sleep for 10 mints
        run: sleep 600

  deploy-job:
    runs-on: ubuntu-latest
    needs: test-job
    steps:
      - name: Download build artifact again
        uses: actions/download-artifact@v4
        with:
          name: build-artifact

      - name: Deploy using artifact
        run: |
          echo "Deploying using artifact..."
          cat artifact.txt
